### ISSUE TITLE
SerialException: write failed: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by parikh5555** [adafruit/Python-Thermal-Printer#26]
Connected Thermal printer with Ubuntu PC but not working
Given all permission to USB port

Traceback (most recent call last):
  File "/media/abhishek/New Volume/OSPL_Energy/ABS sensor tester/Knorr_bremse/thermal_printer.py", line 22, in <module>
    printer.inverseOn()
  File "/media/abhishek/New Volume/OSPL_Energy/ABS sensor tester/Knorr_bremse/Adafruit_Thermal.py", line 402, in inverseOn
    self.writeBytes(29, 66, 1)
  File "/media/abhishek/New Volume/OSPL_Energy/ABS sensor tester/Knorr_bremse/Adafruit_Thermal.py", line 189, in writeBytes
    super(Adafruit_Thermal, self).write(chr(arg))
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 571, in write
    raise SerialException('write failed: {}'.format(e))
SerialException: write failed: [Errno 5] Input/output error

**Comment by ladyada** [comment]
hiya if you purchased from adafruit we do tech support in our forums. thanks!
