### ISSUE TITLE
Issues while running the image print python code on raspberry pi3 (latest stretch raspian lite version)

### ISSUE THREAD

**Issue by titusece** [adafruit/Python-Thermal-Printer#29]
Hello Experts,

**pip3 install pyserial
pip3 install image
python3 sudoku-gfx.py** 

```
pi@camera1-rpi3:~/Python-Thermal-Printer $ python3 sudoku-gfx.py 
Traceback (most recent call last):
  File "sudoku-gfx.py", line 29, in <module>
    printer = Adafruit_Thermal("/dev/serial0", 9600, timeout=5)
  File "/home/pi/Python-Thermal-Printer/Adafruit_Thermal.py", line 96, in __init__
    self.wake()
  File "/home/pi/Python-Thermal-Printer/Adafruit_Thermal.py", line 606, in wake
    self.writeBytes(255)
  File "/home/pi/Python-Thermal-Printer/Adafruit_Thermal.py", line 190, in writeBytes
    super(Adafruit_Thermal, self).write(chr(arg))
  File "/home/pi/.local/lib/python3.5/site-packages/serial/serialposix.py", line 532, in write
    d = to_bytes(data)
  File "/home/pi/.local/lib/python3.5/site-packages/serial/serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: 'ÿ'
pi@camera1-rpi3:~/Python-Thermal-Printer $ 

```
Getting the above error logs while running the sudoku image based printer example.
Can you please help me to solve the issue ?
Thanks for the help.

**Comment by sharkwheels** [comment]
I am also getting this issue. Has anyone come back to this since it was posted?

**Comment by alexholsgrove** [comment]
The code is pretty old now so I imagine it needs to be converted to run under Python3 instead of Python2

**Comment by ConorMatthews** [comment]
Use this library https://github.com/gasperphoenix/Python-Thermal-Printer/tree/Python3andRaspberryPi3

It was forked from the adafruit library. Some examples still need to be ported to python 3, but it is easy to make your own programs. You NEED to change Adafruit_Thermal('/dev/serial0', 19200, timeout=5) to Adafruit_Thermal('/dev/ttyS0', 19200, timeout=5).

Hope this helps 👍

**Comment by gmpmovies** [comment]
> Use this library https://github.com/gasperphoenix/Python-Thermal-Printer/tree/Python3andRaspberryPi3

I tried this, however I'm getting the exact same error as well when running Python 3.7.3 (It works fine with Python 2 though)

**Comment by ladyada** [comment]
try this for py3
https://github.com/adafruit/Adafruit_CircuitPython_Thermal_Printer
