### ISSUE TITLE
SyntaxError - please help -

### ISSUE THREAD

**Issue by cridder** [adafruit/Python-Thermal-Printer#37]
i reinstalled and updated from this repo.

any suggestions.

thanks.

pi@raspberrypi:~/Python-Thermal-Printer $ python printertest.py
Traceback (most recent call last):
  File "printertest.py", line 3, in <module>
    from Adafruit_Thermal import *
  File "/home/pi/Python-Thermal-Printer/Adafruit_Thermal.py", line 725
    def print(self, *args, **kwargs):
            ^
SyntaxError: invalid syntax

**Comment by zackdotcomputer** [comment]
I'm also encountering this - I just commented out that function and the println function for now

**Comment by zackdotcomputer** [comment]
Ok so what did it for me in the end was changing my calls to use `sudo python3` rather than plain-old `sudo python` even though I have `python` alias'd to python3 on my machine. IDK enough about linux and/or python to know why, though.

**Comment by anyu** [comment]
^Right, or change the first line in the sample scripts to `#!/usr/bin/python3`

`print` changed from a [statement to a function](https://docs.python.org/3/whatsnew/3.0.html#print-is-a-function) in Python 3.
